# Generated by Django 2.2.5 on 2019-11-27 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('data', models.CharField(max_length=10)),
                ('hrs_trabalhadas', models.CharField(blank=True, max_length=10)),
                ('total_horas', models.CharField(blank=True, max_length=10)),
                ('hora_extra', models.CharField(blank=True, max_length=10)),
                ('intervalo', models.CharField(blank=True, max_length=10)),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao', models.CharField(max_length=50)),
                ('data_admissao', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo', models.TextField()),
                ('responsavel', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('dia', models.CharField(max_length=10)),
                ('codigo', models.TextField()),
            ],
        ),
    ]
