# Generated by Django 2.2.5 on 2019-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='saida',
            field=models.DateTimeField(null=True),
        ),
    ]
