# Generated by Django 2.2.6 on 2019-11-22 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20191010_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao', models.CharField(max_length=50)),
                ('data_admissao', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo', models.TextField()),
                ('responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Objeto',
        ),
    ]
