# Generated by Django 2.2.6 on 2019-11-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20191122_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='historico',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='historico',
            old_name='objeto',
            new_name='hora_extra',
        ),
        migrations.RenameField(
            model_name='historico',
            old_name='server',
            new_name='intervalo',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='antena',
        ),
        migrations.AddField(
            model_name='historico',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='historico',
            name='saida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
