# Generated by Django 2.2.6 on 2019-11-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20191122_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='entrada',
            new_name='saida_entrada',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='saida',
        ),
    ]
