# Generated by Django 2.2.6 on 2019-11-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20191122_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='entrada_saida',
            new_name='entrada',
        ),
        migrations.AddField(
            model_name='historico',
            name='saida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
