# Generated by Django 2.2.5 on 2019-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20191122_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='responsavel',
            field=models.CharField(max_length=150),
        ),
    ]
