# Generated by Django 2.2.5 on 2019-11-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20191124_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='entrada',
            new_name='passagem',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='hora_extra',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='saida',
        ),
    ]
