# Generated by Django 2.2.5 on 2019-11-24 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20191124_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo', models.TextField()),
                ('intervalo', models.CharField(max_length=10)),
                ('horas_extra', models.CharField(max_length=10)),
                ('total_horas', models.CharField(max_length=10)),
            ],
        ),
    ]
