# Generated by Django 2.2.5 on 2019-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_infodia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoDia',
        ),
    ]
