# Generated by Django 2.2.5 on 2019-11-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_delete_infodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
